name: build and deploy 🚀

on:
  push:
    branches:
      - main # Run on pushes to main
  pull_request:
    branches:
      - main # Run on pull requests targeting main
  workflow_dispatch:
    inputs:
      deploy-gh-pages:
        description: 'Deploy to gh-pages?'
        required: false
        default: 'false'

env:
  DEPLOY_GH_PAGES: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3

      - name: Install pnpm and Dependencies
        run: |
          npm install -g pnpm@10.7.1
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Create .env # create required env variables for the application
        run: |
          touch .env
          echo "CONSUMER_KEY=${{ secrets.CONSUMER_KEY }}" >> .env
          echo "CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }}" >> .env
          echo "WP_SECRET=${{ secrets.WP_SECRET }}" >> .env
          echo "CREW_PW=${{ secrets.CREW_PW }}" >> .env
          echo "GUEST_PW=${{ secrets.GUEST_PW }}" >> .env
          echo "SALT=${{ secrets.SALT }}" >> .env

      - name: 🔨 Compile app
        run: pnpm ng build --configuration=production --base-href ./ --output-path=dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist

  deploy-gh-pages:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist

      - name: 🚀 Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GH_PAGES_TOKEN }}

  deploy-to-wordpress:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.ftp-deploy.outputs.server }}

    env:
      WORDPRESS_HREF: '/festival/'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: dist

      - name: Modify href in index.html
        run: |
          sed -i "s|<base href=['\"].*['\"]>|<base href='${WORDPRESS_HREF}'>|" dist/index.html

      - name: 📂 Sync to WordPress FTP
        id: ftp-deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: konfusius.org
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: festival/
          dangerous-clean-slate: true
