name: deploy to gh-pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      WP_SECRET: ${{ secrets.WP_SECRET }}
      CREW_PW: ${{ secrets.CREW_PW }}
      GUEST_PW: ${{ secrets.GUEST_PW }}
      SALT: ${{ secrets.SALT }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if .env file exists
        run: |
          if [ -f .env ]; then
            echo ".env file exists."
          else
            echo ".env file does not exist."
            exit 1
          fi

      - name: Display content of .env file
        run: |
          cat .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3

      - name: Install pnpm and Dependencies
        run: |
          npm install -g pnpm@10.4.1
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Compile app
        run: pnpm ng build --configuration=production --base-href /festival/

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/festival
          token: ${{ secrets.GH_PAGES_TOKEN }}
