name: deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GUEST_PW: ${{ secrets.GUEST_PW }}
      SALT: ${{ secrets.SALT }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.3

      - name: install pnpm and deps
        run: |
          npm install -g pnpm@10.4.1
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: set environment file
        run: |
          sed -i 's/REPLACE_PASSWORD/${{ secrets.GUEST_PW }}/g' src/environments/environment.prod.ts
          sed -i 's/REPLACE_SALT/${{ secrets.SALT }}/g' src/environments/environment.prod.ts

      - name: compile application
        run: pnpm ng build --configuration=production --base-href /konfusius/

      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/konfusius
          token: ${{ secrets.GH_PAGES_TOKEN }}
