name: deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GUEST_PW: ${{ secrets.GUEST_PW }}
      SALT: ${{ secrets.SALT }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install pnpm and deps
        run: |
          npm install -g @angular/cli --save-dev
          npm install -g pnpm
          pnpm install

      - name: Replace Environment File
        run: |
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  GUEST_PW: \"${{ secrets.GUEST_PW }}\"," >> src/environments/environment.prod.ts
          echo "  SALT: \"${{ secrets.SALT }}\"" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

      - name: Debug Environment File
        run: cat src/environments/environment.prod.ts

      - name: build application
        run: ng build --configuration=production --base-href /konfusius/

      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/konfusius
          token: ${{ secrets.GH_PAGES_TOKEN }}
