name: deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install pnpm and deps
        run: |
          npm install -g pnpm
          pnpm install

      - name: build application
        run: pnpm run build -- --configuration=production --base-href /konfusius/

      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/konfusius
