name: build and deploy 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.3

      - name: Install pnpm and Dependencies
        run: |
          npm install -g pnpm@10.4.1
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Create .env # create required env variables for the application
        run: |
          touch .env
          echo "CONSUMER_KEY=${{ secrets.CONSUMER_KEY }}" >> .env
          echo "CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }}" >> .env
          echo "WP_SECRET=${{ secrets.WP_SECRET }}" >> .env
          echo "CREW_PW=${{ secrets.CREW_PW }}" >> .env
          echo "GUEST_PW=${{ secrets.GUEST_PW }}" >> .env
          echo "SALT=${{ secrets.SALT }}" >> .env

      - name: 🔨 Compile app
        run: pnpm ng build --configuration=production --base-href ./ --output-path=dist

      - name: 🚀 Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy-to-wordpress:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-wordpress.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 📂 Sync to WordPress FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: konfusius.org
          username: f01748f2
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          local-dir: ./dist/
          server-dir: public_html/test-deploy/
