name: deploy to gh-pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.3

      - name: Install Dependencies
        run: |
          npm install -g pnpm@10.4.1
          pnpm config set store-dir .pnpm-store
          pnpm install

      - name: Create .env file
        run: |
          echo "GUEST_PW=${{ secrets.GUEST_PW }}" >> .env
          echo "SALT=${{ secrets.SALT }}" >> .env

      - name: Compile Application
        run: pnpm ng build --configuration=production --base-href /festival/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./dist/festival

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./dist/festival

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./dist/festival
          token: ${{ secrets.GH_PAGES_TOKEN }}
